name: gentoo x32 update
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Preparing rootfs
      run: |
        base_url="https://github.com/$GITHUB_REPOSITORY/releases/latest/download"
        file_name="gentoo-x32.tar.xz"
        wget -nv $base_url/$file_name
        sudo mkdir -v rootfs
        echo " -> Extracting the '$file_name'..."
        sudo tar xpf $file_name -C rootfs
        echo " -> Preparing Virtual Kernel File Systems..."
        sudo mkdir -pv rootfs/{dev,proc,sys,run,tmp}
        sudo mount -v --bind /dev rootfs/dev
        sudo mount -v --bind /dev/pts rootfs/dev/pts
        sudo mount -vt proc proc rootfs/proc
        sudo mount -vt sysfs sysfs rootfs/sys
        sudo mount -vt tmpfs tmpfs rootfs/run
        sudo mount -vt tmpfs tmpfs rootfs/tmp
        if [ -h rootfs/dev/shm ]; then sudo mkdir -pv rootfs/$(readlink rootfs/dev/shm); else sudo mount -vt tmpfs -o nosuid,nodev devshm rootfs/dev/shm; fi
        echo ''
        sudo bash -c "echo -e 'nameserver 1.1.1.1\nnameserver 8.8.8.8' >rootfs/etc/resolv.conf"
        du -shx rootfs/usr/*
        sudo install -do $(id -u) -g $(id -g) rootfs/build
        cp *.sh rootfs/build

    #- name: Rsync gentoo repo
      #run: sudo chroot rootfs /usr/bin/env -i HOME=/root TERM=$TERM PATH=/usr/bin:/usr/sbin /bin/bash --login -c emerge-webrsync
    - name: Run emerge to install packages
      run: sudo chroot rootfs /usr/bin/env -i HOME=/root TERM=$TERM PATH=/usr/bin:/usr/sbin /bin/bash --login -c "cd /build; bash build.sh"
    - name: Package
      run: (cd rootfs; sudo tar cf - --exclude=./dev/* --exclude=./proc/* --exclude=./sys/* --exclude=./run/* --exclude=./tmp/* --exclude=./var/db/repos/* --exclude=./var/cache/* .|xz -T0) > gentoo-x32.tar.xz; echo "TAG_VERSION=$(TZ=GMT-8 date +%Y%m%d.%H)" >> $GITHUB_ENV

    - name: Upload to Releases
      if: ${{ env.TAG_VERSION != '' }}
      uses: softprops/action-gh-release@master
      with:
        tag_name: ${{ env.TAG_VERSION }}
        files: gentoo-*.tar.xz
        fail_on_unmatched_files: true

    - name: Gh login
      if: ${{ failure() }}
      run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token; gh auth setup-git; gh auth status
    - name: Setup tmate ssh session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
